# Examen de Sistemas Inteligentes 2024
## Parte práctica
### Nombre del alumno

Pon aquí tu nombre.

***

**Instrucciones:** Carga el fichero mushroom.csv, y contexta las preguntas debajo de los encabezados.


### Ejercicio 1

Es una red neuronal CNN o NN las cuales son muy buenas para procesar imagenes y convertirlas en datos. Esta red tiene una red de entrada de 128x128*3 y una salida de 8.

### Ejercicio 2

In [171]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder, StandardScaler, MinMaxScaler
from sklearn.model_selection import train_test_split

df = pd.read_csv("./mushroom.csv")

# contar nan y drop
print(df.isna().sum())
df = df.dropna(how="any")
print(df.isna().sum())

cap = df["cap-shape"].to_numpy()
df = df.drop("cap-shape",axis=1)
gillA = df["gill-attachment"].to_numpy()
df = df.drop("gill-attachment", axis=1)
gillC = df["gill-color"].to_numpy()
df = df.drop("gill-color", axis=1)
stem = df["stem-color"].to_numpy()
df = df.drop("stem-color", axis=1)

encoder = OneHotEncoder(sparse_output=False)
cap = encoder.fit_transform(cap.reshape(-1,1))
gillA = encoder.fit_transform(gillA.reshape(-1,1))
gillC = encoder.fit_transform(gillC.reshape(-1,1))
stem = encoder.fit_transform(stem.reshape(-1,1))

Y = df["class"].to_numpy()
X = df.drop("class", axis=1)
X = X.to_numpy()


print(X.shape)
print(Y.shape)
X = np.hstack((X,cap, gillA, gillC, stem))
print(X.shape)

X_scaled = MinMaxScaler().fit_transform(X) #MinMaxScaler para salidas entre 0 y 1

x_train, x_test, y_train, y_test = train_test_split(
    X_scaled, Y,
    test_size=0.2,
    random_state=42,
    stratify=Y
)

print(x_train.shape)
print(x_test.shape)

cap-diameter       2
cap-shape          0
gill-attachment    0
gill-color         0
stem-height        0
stem-width         2
stem-color         0
season             0
class              0
dtype: int64
cap-diameter       0
cap-shape          0
gill-attachment    0
gill-color         0
stem-height        0
stem-width         0
stem-color         0
season             0
class              0
dtype: int64
(54031, 4)
(54031,)
(54031, 43)
(43224, 43)
(10807, 43)


### Ejercicio 3

In [172]:
from sklearn.neural_network import MLPClassifier
import time 

t_p = time.time()
model_p = MLPClassifier(max_iter=270, verbose=1).fit(x_train, y_train)
t_p = time.time() - t_p

Iteration 1, loss = 0.53156240
Iteration 2, loss = 0.35460511
Iteration 3, loss = 0.26986067
Iteration 4, loss = 0.22702673
Iteration 5, loss = 0.20089382
Iteration 6, loss = 0.18347089
Iteration 7, loss = 0.16969942
Iteration 8, loss = 0.15942851
Iteration 9, loss = 0.15100268
Iteration 10, loss = 0.14411385
Iteration 11, loss = 0.13790338
Iteration 12, loss = 0.13234865
Iteration 13, loss = 0.12752368
Iteration 14, loss = 0.12339938
Iteration 15, loss = 0.11934330
Iteration 16, loss = 0.11557098
Iteration 17, loss = 0.11174224
Iteration 18, loss = 0.10885997
Iteration 19, loss = 0.10604489
Iteration 20, loss = 0.10349953
Iteration 21, loss = 0.10147952
Iteration 22, loss = 0.09906517
Iteration 23, loss = 0.09723775
Iteration 24, loss = 0.09445968
Iteration 25, loss = 0.09280279
Iteration 26, loss = 0.09124778
Iteration 27, loss = 0.08967889
Iteration 28, loss = 0.08767881
Iteration 29, loss = 0.08687940
Iteration 30, loss = 0.08507307
Iteration 31, loss = 0.08369525
Iteration 32, los

C:\Users\Deiviss\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (270) reached and the optimization hasn't converged yet.
  warnings.warn(


In [173]:
y_pred_p = model_p.predict(x_test)
print(y_test)
print(y_pred_p)
acc_p = model_p.score(x_test, y_test)
print(acc_p)

[0 1 0 ... 1 1 0]
[0 1 0 ... 1 1 0]
0.9851022485426113


### Ejercicio 4

In [174]:
from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(n_estimators=100,
                                  random_state=42,
                                  max_depth=30,
                                  min_samples_split=2,
                                  min_samples_leaf=1,
                                  n_jobs=-1,
                                  verbose=1
                                  )

t_init = time.time()
rf_model.fit(x_train, y_train)
t_rf = time.time() - t_init



[Parallel(n_jobs=-1)]: Using backend ThreadingBackend with 12 concurrent workers.
[Parallel(n_jobs=-1)]: Done  26 tasks      | elapsed:    0.1s
[Parallel(n_jobs=-1)]: Done 100 out of 100 | elapsed:    0.4s finished


In [175]:
y_pred_rf = rf_model.predict(x_test)
print(y_test)
print(y_pred_rf)
acc_rf = rf_model.score(x_test, y_test)
print(acc_rf)

[0 1 0 ... 1 1 0]
[0 1 0 ... 1 1 0]
0.991301933931711


[Parallel(n_jobs=12)]: Using backend ThreadingBackend with 12 concurrent workers.
[Parallel(n_jobs=12)]: Done  26 tasks      | elapsed:    0.0s
[Parallel(n_jobs=12)]: Done 100 out of 100 | elapsed:    0.0s finished
[Parallel(n_jobs=12)]: Using backend ThreadingBackend with 12 concurrent workers.
[Parallel(n_jobs=12)]: Done  26 tasks      | elapsed:    0.0s
[Parallel(n_jobs=12)]: Done 100 out of 100 | elapsed:    0.0s finished


### Ejercicio 5

In [176]:
from sklearn.metrics import confusion_matrix
print(f"Perceptron: {acc_p:.4f} Time: {t_p:.2f}")
print(f"Random Forest: {acc_rf:.4f} Time: {t_rf:.2f}")

def matrix_view(y_test, y_pred):
    cm = confusion_matrix(y_test, y_pred)

    cm_df = pd.DataFrame(cm, index=['Actual 0 (comestible)', 'Actual 1 (venenoso)'],
    columns=['Pred 0 (comestible)', 'Pred 1 (venenoso)'])
    print(cm_df)

matrix_view(y_test, y_pred_p)
matrix_view(y_test, y_pred_rf)

Perceptron: 0.9851 Time: 35.67
Random Forest: 0.9913 Time: 0.57
                       Pred 0 (comestible)  Pred 1 (venenoso)
Actual 0 (comestible)                 4790                 82
Actual 1 (venenoso)                     79               5856
                       Pred 0 (comestible)  Pred 1 (venenoso)
Actual 0 (comestible)                 4822                 50
Actual 1 (venenoso)                     44               5891
